import type { ToolDefinition } from "@/lib/tool-registry";
import { tf } from "@/lib/registry/lazy";
import {
  Palette,
  Triangle,
  Droplets,
  Box,
  Rows3,
  Shapes,
  Spline,
  LoaderCircle,
  SwitchCamera,
  SquareCheck,
  Zap,
  Columns3,
} from "lucide-react";

export const CSS_TOOLS: ToolDefinition[] = [
  {
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Build linear and radial gradients with live preview.",
    category: "css",
    tier: "standard",
    icon: Palette,
    keywords: ["gradient", "css", "linear", "radial", "background", "preview"],
    commands: ["gradient"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-glassmorphism",
    name: "Glassmorphism Generator",
    description: "Create frosted-glass UI effects with backdrop blur.",
    category: "css",
    icon: Droplets,
    keywords: ["glass", "glassmorphism", "blur", "frosted", "translucent"],
    commands: ["glass"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-triangle-generator",
    name: "CSS Triangle Generator",
    description: "Pure-CSS triangles in any direction, size and color.",
    category: "css",
    icon: Triangle,
    keywords: ["triangle", "css", "shape", "caret", "arrow"],
    commands: ["triangle"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-box-shadow",
    name: "Box Shadow Generator",
    description: "Design layered box-shadows for cards and buttons.",
    category: "css",
    icon: Box,
    keywords: ["box shadow", "shadow", "elevation", "css", "layer"],
    commands: ["shadow"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-border-radius",
    name: "Border Radius Generator",
    description: "Build smooth asymmetric border-radius shapes.",
    category: "css",
    icon: Rows3,
    keywords: ["border radius", "rounded", "curve", "css", "shape"],
    commands: ["radius"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-background-patterns",
    name: "CSS Background Patterns",
    description: "Seamless repeating patterns made of pure gradients.",
    category: "css",
    icon: Shapes,
    keywords: ["pattern", "background", "seamless", "repeating", "css"],
    commands: ["pattern"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-clip-path",
    name: "CSS Clip Path Generator",
    description: "Visual polygons to clip any element.",
    category: "css",
    icon: Spline,
    keywords: ["clip path", "polygon", "shape", "clip", "css"],
    commands: ["clip"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-cubic-bezier",
    name: "Cubic Bezier Generator",
    description: "Tune easing curves for buttery animations.",
    category: "css",
    icon: Spline,
    keywords: ["cubic bezier", "easing", "curve", "animation", "transition"],
    commands: ["bezier"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-loader-generator",
    name: "CSS Loader Generator",
    description: "Spinners and loaders with customizable colors.",
    category: "css",
    icon: LoaderCircle,
    keywords: ["loader", "spinner", "loading", "animation", "css"],
    commands: ["loader"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-switch-generator",
    name: "CSS Toggle Switch",
    description: "Generate styled checkbox-based toggle switches.",
    category: "css",
    icon: SwitchCamera,
    keywords: ["switch", "toggle", "ios", "checkbox", "css"],
    commands: ["switch"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-checkbox-generator",
    name: "CSS Checkbox Generator",
    description: "Custom checkboxes with animations and colors.",
    category: "css",
    icon: SquareCheck,
    keywords: ["checkbox", "check", "custom", "css", "form"],
    commands: ["checkbox"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-text-glitch",
    name: "Text Glitch Generator",
    description: "Cyberpunk RGB-split glitch effects with clip-path.",
    category: "css",
    icon: Zap,
    keywords: ["glitch", "text", "effect", "rgb", "cyberpunk", "css"],
    commands: ["glitch"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
  {
    slug: "css-grid-generator",
    name: "CSS Grid Generator",
    description:
      "Lay out a css-grid with configurable columns, gaps and templates.",
    category: "css",
    icon: Columns3,
    keywords: ["grid", "columns", "layout", "template", "gaps", "css"],
    commands: ["grid"],
    status: "ready",
    component: tf(() => import("@/components/tools/css/css-generators")),
  },
];
