import type { ToolDefinition } from "@/lib/tool-registry";
import { tf } from "@/lib/registry/lazy";
import {
  Lock,
  KeySquare,
  Shield,
  KeyRound,
  Binary,
  ListChecks,
  ScanText,
  Combine,
  GitCompareArrows,
  Split,
  SwitchCamera,
  Search,
  Eraser,
  Terminal,
  FileSearch,
  Timer,
  WandSparkles,
  FolderTree,
  FileCode2,
  FileDiff,
  SquareCheck,
  Braces,
  TextCursorInput,
  Hexagon,
  Spline,
  Droplets,
  Palette,
} from "lucide-react";

export const DEV_TOOLS: ToolDefinition[] = [
  // --- Crypto (WebCrypto, fully in-browser) ---
  {
    slug: "aes-cipher",
    name: "AES Encrypt / Decrypt",
    description:
      "Encrypt and decrypt text with AES-128/192/256 in CBC or GCM mode.",
    category: "crypto",
    tier: "standard",
    icon: Lock,
    keywords: ["aes", "encrypt", "decrypt", "cipher", "cbc", "gcm", "aes256"],
    commands: ["aes"],
    status: "ready",
    component: tf(() => import("@/components/tools/crypto/crypto-tools")),
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    description:
      "Compute HMAC-MD5/SHA1/SHA256/SHA512 signatures with any secret key.",
    category: "crypto",
    icon: KeySquare,
    keywords: ["hmac", "signature", "auth", "sha", "secret", "key"],
    commands: ["hmac"],
    status: "ready",
    component: tf(() => import("@/components/tools/crypto/crypto-tools")),
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description:
      "Decode, segment and verify JWT tokens without sending them anywhere.",
    category: "crypto",
    icon: Shield,
    keywords: ["jwt", "token", "decode", "verify", "authentication", "payload"],
    commands: ["jwt"],
    status: "ready",
    component: tf(() => import("@/components/tools/crypto/crypto-tools")),
  },
  {
    slug: "crypto-key-gen",
    name: "Crypto Key Generator",
    description: "Generate random keys, salts, IVs and secrets of any length.",
    category: "crypto",
    icon: KeyRound,
    keywords: ["key", "salt", "iv", "secret", "random", "entropy", "hex"],
    commands: ["keygen", "secret"],
    status: "ready",
    component: tf(() => import("@/components/tools/crypto/crypto-tools")),
  },

  // --- Bitmap / binary ---
  {
    slug: "radix-converter",
    name: "Base / Radix Converter",
    description:
      "Convert numbers between binary, octal, decimal and hex (2–36).",
    category: "bitmap",
    tier: "standard",
    icon: Binary,
    keywords: ["radix", "base", "binary", "hex", "octal", "decimal", "base64"],
    commands: ["radix", "base"],
    status: "ready",
    component: tf(() => import("@/components/tools/bitmap/bitmap-tools")),
  },
  {
    slug: "bitwise-calculator",
    name: "Bitwise Calculator",
    description: "AND, OR, XOR, NOT and shifts on int8/16/32/64 values.",
    category: "bitmap",
    icon: Binary,
    keywords: ["bitwise", "binary", "and", "xor", "or", "shift", "mask"],
    commands: ["bitwise"],
    status: "ready",
    component: tf(() => import("@/components/tools/bitmap/bitmap-tools")),
  },
  {
    slug: "bit-flags",
    name: "Bit Flags Builder",
    description: "Combine and decode 8/16/32-bit permission-style bit flags.",
    category: "bitmap",
    icon: ListChecks,
    keywords: [
      "flags",
      "bitmask",
      "permissions",
      "bits",
      "enum",
      "flags builder",
    ],
    commands: ["flags"],
    status: "ready",
    component: tf(() => import("@/components/tools/bitmap/bitmap-tools")),
  },
  {
    slug: "binary-viewer",
    name: "Binary Viewer",
    description: "Inspect a string as UTF-8 bytes, codepoints and binary.",
    category: "bitmap",
    icon: ScanText,
    keywords: ["binary", "bytes", "hex", "viewer", "dump", "bits"],
    commands: ["binary"],
    status: "ready",
    component: tf(() => import("@/components/tools/bitmap/bitmap-tools")),
  },

  // --- Set operations ---
  {
    slug: "set-union",
    name: "Set Union",
    description: "Merge two lists of lines, keeping each unique item once.",
    category: "set",
    tier: "advanced",
    icon: Combine,
    keywords: ["set", "union", "merge", "combine", "unique"],
    commands: ["set union"],
    status: "ready",
    component: tf(() => import("@/components/tools/set/set-tools")),
  },
  {
    slug: "set-intersection",
    name: "Set Intersection",
    description: "Items present in both lists of lines.",
    category: "set",
    icon: GitCompareArrows,
    keywords: ["set", "intersection", "common", "both", "overlap"],
    commands: ["set intersection"],
    status: "ready",
    component: tf(() => import("@/components/tools/set/set-tools")),
  },
  {
    slug: "set-difference",
    name: "Set Difference",
    description: "Items in list A that are NOT in list B.",
    category: "set",
    icon: Split,
    keywords: ["set", "difference", "subtract", "minus"],
    commands: ["set difference"],
    status: "ready",
    component: tf(() => import("@/components/tools/set/set-tools")),
  },
  {
    slug: "set-symmetric-difference",
    name: "Symmetric Difference",
    description: "Items in either list but NOT in both (A △ B).",
    category: "set",
    icon: SwitchCamera,
    keywords: ["set", "symmetric", "xor", "exclusive", "not both"],
    commands: ["set xor"],
    status: "ready",
    component: tf(() => import("@/components/tools/set/set-tools")),
  },
  {
    slug: "set-membership",
    name: "Set Membership Checker",
    description: "Test which items of a list exist in another list.",
    category: "set",
    icon: Search,
    keywords: ["set", "membership", "contains", "include", "filter", "exists"],
    commands: ["set membership"],
    status: "ready",
    component: tf(() => import("@/components/tools/set/set-tools")),
  },
  {
    slug: "set-dedupe",
    name: "Dedupe Lines",
    description: "Remove duplicate lines while preserving order.",
    category: "set",
    icon: Eraser,
    keywords: ["dedupe", "deduplicate", "unique", "duplicate", "distinct"],
    commands: ["dedupe"],
    status: "ready",
    component: tf(() => import("@/components/tools/set/set-tools")),
  },

  // --- Linux ---
  {
    slug: "chmod-calculator",
    name: "chmod Calculator",
    description: "Convert symbolic (rwx) permissions to octal and back.",
    category: "linux",
    tier: "standard",
    icon: Shield,
    keywords: ["chmod", "permissions", "rwx", "octal", "symbolic", "770"],
    commands: ["chmod"],
    status: "ready",
    component: tf(() => import("@/components/tools/linux/linux-tools")),
  },
  {
    slug: "permissions-decoder",
    name: "ls -l Permissions Decoder",
    description: "Decode a drwxr-xr-x permission string into its meaning.",
    category: "linux",
    icon: FileSearch,
    keywords: ["ls", "permissions", "decode", "drwx", "owner", "group"],
    commands: ["ls -l"],
    status: "ready",
    component: tf(() => import("@/components/tools/linux/linux-tools")),
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse any cron expression and list the next five runs.",
    category: "linux",
    tier: "advanced",
    icon: Timer,
    keywords: ["cron", "parser", "schedule", "expression", "job"],
    commands: ["cron parse"],
    status: "ready",
    component: tf(() => import("@/components/tools/linux/linux-tools")),
  },
  {
    slug: "cron-generator",
    name: "Cron Generator",
    description: "Build cron expressions visually minute by minute.",
    category: "linux",
    icon: WandSparkles,
    keywords: ["cron", "generator", "schedule", "every", "expression"],
    commands: ["cron generate"],
    status: "ready",
    component: tf(() => import("@/components/tools/linux/linux-tools")),
  },
  {
    slug: "path-utils",
    name: "POSIX Path Utilities",
    description: "Join, resolve, normalize, dirname & basename paths.",
    category: "linux",
    icon: FolderTree,
    keywords: ["path", "posix", "dirname", "basename", "join", "linux"],
    commands: ["path"],
    status: "ready",
    component: tf(() => import("@/components/tools/linux/linux-tools")),
  },
  {
    slug: "uid-gid-table",
    name: "UID & GID Table",
    description: "Well-known Linux UIDs/GIDs for users, daemons and groups.",
    category: "linux",
    icon: ListChecks,
    keywords: ["uid", "gid", "linux", "users", "root", "daemon"],
    commands: ["uid", "gid"],
    status: "ready",
    component: tf(() => import("@/components/tools/linux/linux-tools")),
  },

  // --- XML ---
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Pretty-print XML with configurable indentation.",
    category: "xml",
    tier: "standard",
    icon: FileCode2,
    keywords: ["xml", "format", "pretty", "indent", "beautify"],
    commands: ["xml format"],
    status: "ready",
    component: tf(() => import("@/components/tools/xml/xml-tools")),
  },
  {
    slug: "xml-minifier",
    name: "XML Minifier",
    description: "Compact XML by removing ignorable whitespace.",
    category: "xml",
    icon: FileDiff,
    keywords: ["xml", "minify", "compact", "space", "size"],
    commands: ["xml minify"],
    status: "ready",
    component: tf(() => import("@/components/tools/xml/xml-tools")),
  },
  {
    slug: "xml-validator",
    name: "XML Validator",
    description: "Validate XML well-formedness and show the exact error.",
    category: "xml",
    icon: SquareCheck,
    keywords: ["xml", "validate", "wellformed", "error", "parse"],
    commands: ["xml validate"],
    status: "ready",
    component: tf(() => import("@/components/tools/xml/xml-tools")),
  },
  {
    slug: "xml-json-converter",
    name: "XML ⇄ JSON Converter",
    description: "Convert simple XML documents to JSON and back.",
    category: "xml",
    icon: Braces,
    keywords: ["xml", "json", "convert", "transform"],
    commands: ["xml json"],
    status: "ready",
    component: tf(() => import("@/components/tools/xml/xml-tools")),
  },

  // --- UTF-8 ---
  {
    slug: "utf8-encoder",
    name: "UTF-8 Encoder",
    description: "Encode and decode UTF-8 bytes from text.",
    category: "utf8",
    tier: "advanced",
    icon: TextCursorInput,
    keywords: ["utf8", "utf-8", "encode", "decode", "bytes"],
    commands: ["utf8"],
    status: "ready",
    component: tf(() => import("@/components/tools/utf8/utf8-tools")),
  },
  {
    slug: "codepoint-inspector",
    name: "Codepoint Inspector",
    description: "Inspect every Unicode codepoint and its decomposition.",
    category: "utf8",
    icon: ScanText,
    keywords: ["codepoint", "unicode", "char", "utf-16", "utf-32"],
    commands: ["codepoint"],
    status: "ready",
    component: tf(() => import("@/components/tools/utf8/utf8-tools")),
  },
  {
    slug: "utf8-validator",
    name: "UTF-8 Validator",
    description: "Check whether a byte sequence is valid UTF-8.",
    category: "utf8",
    icon: SquareCheck,
    keywords: ["utf8", "validate", "bytes", "invalid", "mojibake"],
    commands: ["utf8 validate"],
    status: "ready",
    component: tf(() => import("@/components/tools/utf8/utf8-tools")),
  },
  {
    slug: "bom-utilities",
    name: "BOM Utilities",
    description: "Add, strip and inspect UTF-8/16/32 byte-order marks.",
    category: "utf8",
    icon: FileSearch,
    keywords: ["bom", "byte order mark", "ef bb bf", "utf8", "header"],
    commands: ["bom"],
    status: "ready",
    component: tf(() => import("@/components/tools/utf8/utf8-tools")),
  },
  {
    slug: "escape-sequences",
    name: "Escape / Unescape",
    description: "Escape & unescape \\n \\t \\uXXXX and hex sequences.",
    category: "utf8",
    icon: Braces,
    keywords: ["escape", "unescape", "backslash", "newline", "unicode escape"],
    commands: ["escape"],
    status: "ready",
    component: tf(() => import("@/components/tools/utf8/utf8-tools")),
  },

  // --- Color ---
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Build a cohesive palette from a seed color.",
    category: "color",
    tier: "standard",
    icon: Palette,
    keywords: ["palette", "color", "scheme", "design", "harmony"],
    commands: ["palette"],
    status: "ready",
    component: tf(() => import("@/components/tools/color/color-tools")),
  },
  {
    slug: "hex-to-rgba",
    name: "Hex → RGBA",
    description: "Convert HEX colors to rgba() effortlessly.",
    category: "color",
    icon: Hexagon,
    keywords: ["hex", "rgba", "convert", "color", "css"],
    commands: ["hex to rgba"],
    status: "ready",
    component: tf(() => import("@/components/tools/color/color-tools")),
  },
  {
    slug: "rgba-to-hex",
    name: "RGBA → Hex",
    description: "Convert rgba() colors back to #rrggbb or #rrggbbaa.",
    category: "color",
    icon: Hexagon,
    keywords: ["rgba", "hex", "convert", "color", "css"],
    commands: ["rgba to hex"],
    status: "ready",
    component: tf(() => import("@/components/tools/color/color-tools")),
  },
  {
    slug: "color-shades",
    name: "Color Shades Generator",
    description: "Generate tints and shades from 10% to 90%.",
    category: "color",
    icon: Spline,
    keywords: ["shades", "tints", "lighten", "darken", "color", "scale"],
    commands: ["shades"],
    status: "ready",
    component: tf(() => import("@/components/tools/color/color-tools")),
  },
  {
    slug: "color-mixer",
    name: "Color Mixer",
    description: "Blend two colors with a mixing ratio.",
    category: "color",
    icon: Droplets,
    keywords: ["mix", "blend", "color", "ratio", "gradient"],
    commands: ["mix colors"],
    status: "ready",
    component: tf(() => import("@/components/tools/color/color-tools")),
  },
];
