checks:
    javascript: true

build:
    image: default-jammy
    nodes:
        build:
            commands:
                - checkout-code ~/build
                - cd ~/build
                - corepack enable
                - corepack prepare pnpm@latest-10 --activate
                - pnpm install --frozen-lockfile
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
