name: Sentry Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Sentry CLI
        run: npm install -g @sentry/cli

      - name: Generate release version
        id: version
        run: |
          VERSION="aiot@0.$(date +%Y%m%d%H%M%S)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create js/sentry-release.js
        run: |
          echo "const SENTRY_RELEASE = '$VERSION';" > js/sentry-release.js

      - name: Create Sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          sentry-cli releases new "$VERSION"
          sentry-cli releases set-commits "$VERSION" --auto
          sentry-cli releases finalize "$VERSION"

      - name: Create Deploy
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          sentry-cli releases deploys "$VERSION" new -e production